services:
  behave:
    container_name: behave
    build:
      context: .
      dockerfile: ./docker/py310/Dockerfile
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - ./:/py310
      - /tmp/.X11-unix:/tmp/.X11-unix # GUI
      - /mnt/wslg:/mnt/wslg
    ports:
      - "${PY310_PORT}:${PY310_PORT}"
      